# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
dist: focal
r:
    - release
    - devel
r_binary_packages:
    - bitops
    - sets
    - digest
    - rpart
    - rpart.plot
    - parallel
    - plotrix
    - cluster
    - stringr
    - lavaan
    - expm
    - lavaan
    - tidyr
    - viridis
    - ggplot2
    - methods
    - strucchange
    - sandwich
    - zoo
    - crayon
    - clisymbols
    - testthat
    